import type { CoderTask, CommandExecutor } from '../coder/coder.types';

export async function createPullRequest(
  worktreePath: string,
  branch: string,
  task: CoderTask,
  exec: CommandExecutor,
): Promise<string | null> {
  const pushResult = await exec(`git push -u origin ${branch}`, worktreePath);
  if (pushResult.exitCode !== 0) return null;

  const title = `#${task.issueNumber} ${task.title}`;
  const body = buildPrBody(task);
  const prResult = await exec(`gh pr create --title ${quote(title)} --body ${quote(body)}`, worktreePath);

  if (prResult.exitCode !== 0) return null;

  return prResult.output.trim();
}

function buildPrBody(task: CoderTask): string {
  const lines = [`Closes #${task.issueNumber}`, '', '## Summary', '', task.body];

  if (task.acceptanceCriteria.length > 0) {
    lines.push('', '## Acceptance Criteria', '');
    for (const criterion of task.acceptanceCriteria) {
      lines.push(`- [x] ${criterion}`);
    }
  }

  lines.push('', '---', 'Generated by Forge 🔨');

  return lines.join('\n');
}

function quote(str: string): string {
  const escaped = str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/`/g, '\\`')
    .replace(/!/g, '\\!');
  return `"${escaped}"`;
}
